### ISSUE TITLE
grunt-sails-linker removes external css links like google fonts 

### ISSUE THREAD

**Issue by sudhirjena** [sailsjs/grunt-sails-linker#19]
When running sails lift, sails linker removes 

```
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css"> 
```

from assets/index.html

**Comment by mikermcneil** [comment]
@sudhirjena Hmm, I wasn't able to replicate in the current version.  Are you still seeing this?  It should only be removing stuff between the special delimiters: in this case, `<!--STYLES-->` and `<!--STYLES END-->`. 

![image](https://cloud.githubusercontent.com/assets/618009/19463374/1c1081c6-94b9-11e6-8c67-3903a679c54d.png)

**Comment by sudhirjena** [comment]
Closing the issue as was related to incorrect grunt configuration. Sorry for the confusion
